# Generated by Django 5.1.1 on 2024-10-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_remove_product_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='oferta',
            field=models.BooleanField(default=False),
        ),
    ]
