# Generated by Django 5.1.1 on 2024-10-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_product_activo_product_oferta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='product',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
